spring:
  datasource:
    url: jdbc:mysql:///software?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: py12345646
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181