spring:
  datasource:
    url: jdbc:mysql:///software?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&zeroDateTimeBehavior=convertToNull
    username: root
    password: py12345646
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true


server:
  port: 8181